# This is the main configuration file of your Dancer2 app
# env-related settings should go to environments/$env.yml
# all the settings in this file will be loaded at Dancer's startup.

# Your application's name
appname: "IMGames"

# The default layout to use for your application (located in
# views/layouts/main.tt)
layout: "main"

# when the charset is set to UTF-8 Dancer2 will handle for you
# all the magic of encoding and decoding. You should not care
# about unicode within your app when this setting is set (recommended).
charset: "UTF-8"

# template engine
# simple: default and very basic template engine
# template_toolkit: TT

template: "template_toolkit"

auto_page: 1

session: Cookie

plugins:

engines:
  template:
    template_toolkit:
      start_tag: '<%'
      end_tag:   '%>'
  session:
    YAML:
      session_dir: "./sessions"
      cookie_duration: 3600    # Default cookie timeout in seconds, 1 hour
      is_secure: 1
    Cookie:
      secret_key: 'entire works of Shakespeare'
      default_duration: 604800

