---
schema:
  procedures: {}
  tables:
    acl:
      constraints:
        - deferrable: 1
          expression: ''
          fields:
            - id
          match_type: ''
          name: ''
          on_delete: ''
          on_update: ''
          options: []
          reference_fields: []
          reference_table: ''
          type: PRIMARY KEY
      fields:
        access_level:
          data_type: integer
          default_value: ~
          is_nullable: 0
          is_primary_key: 0
          is_unique: 0
          name: access_level
          order: 3
          size:
            - 5
        created_on:
          data_type: DateTime
          default_value: 2016-10-04T18:36:13
          is_nullable: 0
          is_primary_key: 0
          is_unique: 0
          name: created_on
          order: 4
          size:
            - 0
        id:
          data_type: integer
          default_value: ~
          is_auto_increment: 1
          is_nullable: 0
          is_primary_key: 1
          is_unique: 0
          name: id
          order: 1
          size:
            - 20
        name:
          data_type: varchar
          default_value: ~
          is_nullable: 0
          is_primary_key: 0
          is_unique: 0
          name: name
          order: 2
          size:
            - 30
        updated_on:
          data_type: Timestamp
          default_value: ~
          is_nullable: 1
          is_primary_key: 0
          is_unique: 0
          name: updated_on
          order: 5
          size:
            - 0
      indices: []
      name: acl
      options: []
      order: 1
    users:
      constraints:
        - deferrable: 1
          expression: ''
          fields:
            - id
          match_type: ''
          name: ''
          on_delete: ''
          on_update: ''
          options: []
          reference_fields: []
          reference_table: ''
          type: PRIMARY KEY
        - deferrable: 1
          expression: ''
          fields:
            - acl_id
          match_type: ''
          name: users_fk_acl_id
          on_delete: CASCADE
          on_update: CASCADE
          options: []
          reference_fields:
            - id
          reference_table: acl
          type: FOREIGN KEY
      fields:
        acl_id:
          data_type: integer
          default_value: 1
          is_nullable: 0
          is_primary_key: 0
          is_unique: 0
          name: acl_id
          order: 8
          size:
            - 2
        birthdate:
          data_type: date
          default_value: ~
          is_nullable: 0
          is_primary_key: 0
          is_unique: 0
          name: birthdate
          order: 6
          size:
            - 0
        confirmed:
          data_type: integer
          default_value: 0
          is_nullable: 0
          is_primary_key: 0
          is_unique: 0
          name: confirmed
          order: 9
          size:
            - 1
        created_on:
          data_type: DateTime
          default_value: 2016-10-04T18:36:13
          is_nullable: 0
          is_primary_key: 0
          is_unique: 0
          name: created_on
          order: 10
          size:
            - 0
        email:
          data_type: varchar
          default_value: ~
          is_nullable: 0
          is_primary_key: 0
          is_unique: 0
          name: email
          order: 7
          size:
            - 255
        first_name:
          data_type: varchar
          default_value: ~
          is_nullable: 0
          is_primary_key: 0
          is_unique: 0
          name: first_name
          order: 3
          size:
            - 255
        id:
          data_type: integer
          default_value: ~
          is_auto_increment: 1
          is_nullable: 0
          is_primary_key: 1
          is_unique: 0
          name: id
          order: 1
          size:
            - 20
        last_name:
          data_type: varchar
          default_value: ~
          is_nullable: 0
          is_primary_key: 0
          is_unique: 0
          name: last_name
          order: 4
          size:
            - 255
        password:
          data_type: char
          default_value: ~
          is_nullable: 0
          is_primary_key: 0
          is_unique: 0
          name: password
          order: 5
          size:
            - 73
        updated_on:
          data_type: Timestamp
          default_value: ~
          is_nullable: 1
          is_primary_key: 0
          is_unique: 0
          name: updated_on
          order: 11
          size:
            - 0
        username:
          data_type: varchar
          default_value: ~
          is_nullable: 0
          is_primary_key: 0
          is_unique: 0
          name: username
          order: 2
          size:
            - 30
      indices:
        - fields:
            - acl_id
          name: users_idx_acl_id
          options: []
          type: NORMAL
      name: users
      options: []
      order: 2
  triggers: {}
  views: {}
translator:
  add_drop_table: 0
  filename: ~
  no_comments: 0
  parser_args:
    sources:
      - ACL
      - User
  parser_type: SQL::Translator::Parser::DBIx::Class
  producer_args: {}
  producer_type: SQL::Translator::Producer::YAML
  show_warnings: 0
  trace: 0
  version: 0.11021
