-- Deploy imgames:acl to mysql
-- requires: appuser

BEGIN;

CREATE TABLE IF NOT EXISTS roles (
  id BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  role VARCHAR(30) NOT NULL,
  created_on DATETIME NOT NULL DEFAULT NOW(),
  updated_on TIMESTAMP NULL DEFAULT NULL
);

COMMIT;
